name: test-json
decription: Action to generate a custom task definition json file

inputs:
  environment:
    description: 'Environment Name'
    required: true
    default: dev
  test:
    description: 'Test it'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: print echo
      shell: bash
      run: |
        echo ":redsiren: soo:print context inside action"
        echo "${{ github.jobs }}"
        echo "${{ github.repository }}"
        echo "${{ github.server_url }}"
        echo "${{ github.run_id }}"
        echo "${{ inputs.test }}"
