# This is a basic workflow to help you get started with Actions

name: Create a tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: main
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createTagAndRef:
    name: create a Tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Create a Tag
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.payload.repository.owner)
            const tagResponse = await github.request('POST /repos/{owner}/{repo}/git/tags', {
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.url,
              tag: 'v0.0.1',
              message: 'initial version',
              object: context.payload.sha,
              type: 'commit',
            })
            console.log("response")
            console.log(tagResponse)
            const refResponse = octokit.request('GET /repos/{owner}/{repo}/git/ref/{ref}', {
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.url,
              ref: response.data.sha
            })

            console.log(refResponse)

           
