---
name: on-failure

on: 
  workflow_run:
    workflows:
      [create-a-tag]
    types: [completed]
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conlusions == 'FAILURE' }}
    steps:
      - name: Send message
      - name: checkout
        uses: actions/checkout@v3
        shell: bash
        run: |
          echo "${{ github.server_url }}"
     
